M48
; DRILL file KiCad 10.0.4 date 2026-08-12T17:59:27
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-12T17:59:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X159.0Y-84.25
X159.0Y-111.25
X204.0Y-84.25
X204.0Y-111.25
T2
X169.925Y-121.425
X194.75Y-80.925
M30
